# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
# permalink: /:categories/:year/:month/:day/:title 
permalink: /blog/:year/:month/:title.html 
include: ['.htaccess']
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "CNAME", "Gemfile", "Gemfile.lock"]
markdown: redcarpet
highlights: pygments
lsi: false
timezone: Asia/Shanghai
safe: false

JB :
  ASSET_PATH : http://zhu8.qiniudn.com/assets
  IMAGE_PATH : http://zhu8.qiniudn.com/images
# auto: true # deprecated

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
url: http://git.hupantingxue.com
title: ChenJun(hupantingxue)-浮生志
tagline: On The Way to Philistinism...
about: <a href="http://jdkr.cn/"><strong>hupantingxue</strong></a>ChenJun(hupantingxue)的个人网站，江西人士，86年生人，电子产品自虐狂，<a href="http://chenjun.com/wang2/"><strong>王小波</strong></a>门下走狗，欢迎<strong>Fork</strong>本站@<a href="https://github.com/hupantingxue/blog/fork">Github</a>。
author:
  name: hupantingxue(hupantingxue)
  email: hupantingxue@126.com
  github: hupantingxue
  twitter: hupantingxue
  facebook: ichenjun
  googleplus: hupantingxue
  feedburner : hupantingxue/github
